# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0.xci
# IP: The module: 'dma_sys_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0.xci
# IP: The module: 'dma_sys_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
