# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/dma_sys_system_ila_0_0.xci
# IP: The module: 'dma_sys_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/bd_e02d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e02d || ORIG_REF_NAME==bd_e02d} -quiet] -quiet

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_0/bd_e02d_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e02d_ila_lib_0 || ORIG_REF_NAME==bd_e02d_ila_lib_0} -quiet] -quiet

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_1/bd_e02d_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e02d_g_inst_0 || ORIG_REF_NAME==bd_e02d_g_inst_0} -quiet] -quiet

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e02d_ila_lib_0 || ORIG_REF_NAME==bd_e02d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_0/bd_e02d_ila_lib_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/bd_e02d_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/dma_sys_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/dma_sys_system_ila_0_0.xci
# IP: The module: 'dma_sys_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/bd_e02d.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e02d || ORIG_REF_NAME==bd_e02d} -quiet] -quiet

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_0/bd_e02d_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e02d_ila_lib_0 || ORIG_REF_NAME==bd_e02d_ila_lib_0} -quiet] -quiet

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_1/bd_e02d_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_e02d_g_inst_0 || ORIG_REF_NAME==bd_e02d_g_inst_0} -quiet] -quiet

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_e02d_ila_lib_0 || ORIG_REF_NAME==bd_e02d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_0/bd_e02d_ila_lib_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/bd_e02d_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/dma_sys_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
