vlib work
vlib riviera

vlib riviera/xil_defaultlib
vlib riviera/xpm
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/smartconnect_v1_0
vlib riviera/axi_protocol_checker_v2_0_0
vlib riviera/axi_vip_v1_1_0
vlib riviera/processing_system7_vip_v1_0_2
vlib riviera/lib_pkg_v1_0_2
vlib riviera/fifo_generator_v13_2_0
vlib riviera/lib_fifo_v1_0_9
vlib riviera/lib_srl_fifo_v1_0_2
vlib riviera/lib_cdc_v1_0_2
vlib riviera/axi_datamover_v5_1_16
vlib riviera/axi_sg_v4_1_7
vlib riviera/axi_dma_v7_1_15
vlib riviera/proc_sys_reset_v5_0_12
vlib riviera/xlconstant_v1_1_3
vlib riviera/gigantic_mux
vlib riviera/generic_baseblocks_v2_1_0
vlib riviera/axi_data_fifo_v2_1_13
vlib riviera/axi_register_slice_v2_1_14
vlib riviera/axi_protocol_converter_v2_1_14

vmap xil_defaultlib riviera/xil_defaultlib
vmap xpm riviera/xpm
vmap axi_infrastructure_v1_1_0 riviera/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 riviera/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_0 riviera/axi_protocol_checker_v2_0_0
vmap axi_vip_v1_1_0 riviera/axi_vip_v1_1_0
vmap processing_system7_vip_v1_0_2 riviera/processing_system7_vip_v1_0_2
vmap lib_pkg_v1_0_2 riviera/lib_pkg_v1_0_2
vmap fifo_generator_v13_2_0 riviera/fifo_generator_v13_2_0
vmap lib_fifo_v1_0_9 riviera/lib_fifo_v1_0_9
vmap lib_srl_fifo_v1_0_2 riviera/lib_srl_fifo_v1_0_2
vmap lib_cdc_v1_0_2 riviera/lib_cdc_v1_0_2
vmap axi_datamover_v5_1_16 riviera/axi_datamover_v5_1_16
vmap axi_sg_v4_1_7 riviera/axi_sg_v4_1_7
vmap axi_dma_v7_1_15 riviera/axi_dma_v7_1_15
vmap proc_sys_reset_v5_0_12 riviera/proc_sys_reset_v5_0_12
vmap xlconstant_v1_1_3 riviera/xlconstant_v1_1_3
vmap gigantic_mux riviera/gigantic_mux
vmap generic_baseblocks_v2_1_0 riviera/generic_baseblocks_v2_1_0
vmap axi_data_fifo_v2_1_13 riviera/axi_data_fifo_v2_1_13
vmap axi_register_slice_v2_1_14 riviera/axi_register_slice_v2_1_14
vmap axi_protocol_converter_v2_1_14 riviera/axi_protocol_converter_v2_1_14

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93 \
"C:/Xilinx/Vivado/2017.3/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5c1/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/8b42/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_2  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_processing_system7_0_0/sim/dma_sys_processing_system7_0_0.v" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/8c4b/FPMult_SinglePrecision_Rieee.v" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/8c4b/inverter.v" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_inverter_0_0/sim/dma_sys_inverter_0_0.v" \

vcom -work lib_pkg_v1_0_2 -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_0  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/0798/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_0 -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/0798/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_0  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/0798/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_9 -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/462e/hdl/lib_fifo_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work lib_cdc_v1_0_2 -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_16 -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/0377/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vcom -work axi_sg_v4_1_7 -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/8316/hdl/axi_sg_v4_1_rfs.vhd" \

vcom -work axi_dma_v7_1_15 -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/9eb7/hdl/axi_dma_v7_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/sim/dma_sys_axi_dma_0_0.vhd" \

vcom -work proc_sys_reset_v5_0_12 -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_rst_ps7_0_50M_0/sim/dma_sys_rst_ps7_0_50M_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/sim/bd_954e.v" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/786b/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_10/sim/bd_954e_s00a2s_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_16/sim/bd_954e_s01a2s_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/92d2/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_20/sim/bd_954e_m00s2a_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/fa70/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_26/sim/bd_954e_m00e_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_21/sim/bd_954e_m00arn_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_22/sim/bd_954e_m00rn_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_23/sim/bd_954e_m00awn_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_24/sim/bd_954e_m00wn_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_25/sim/bd_954e_m00bn_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_17/sim/bd_954e_sawn_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_18/sim/bd_954e_swn_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_19/sim/bd_954e_sbn_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/8ad6/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_13/sim/bd_954e_s01mmu_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/0f5f/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_14/sim/bd_954e_s01tr_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/925a/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_15/sim/bd_954e_s01sic_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_11/sim/bd_954e_sarn_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_12/sim/bd_954e_srn_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_7/sim/bd_954e_s00mmu_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_8/sim/bd_954e_s00tr_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_9/sim/bd_954e_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/1b0c/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -sv2k12 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_2/sim/bd_954e_arsw_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_3/sim/bd_954e_rsw_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_4/sim/bd_954e_awsw_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_5/sim/bd_954e_wsw_0.sv" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_6/sim/bd_954e_bsw_0.sv" \

vlog -work xlconstant_v1_1_3  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_0/sim/bd_954e_one_0.v" \

vcom -work xil_defaultlib -93 \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_1/sim/bd_954e_psr_aclk_0.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/sim/dma_sys_axi_smc_1.v" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/sim/bd_e02d.v" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_0/sim/bd_e02d_ila_lib_0.v" \

vlog -work gigantic_mux  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d322/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_1/bd_e02d_g_inst_0_gigantic_mux.v" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_1/sim/bd_e02d_g_inst_0.v" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/sim/dma_sys_system_ila_0_0.v" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/sim/dma_sys.v" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_13  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/74ae/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_14  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a259/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_protocol_converter_v2_1_14  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/33cc/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/ec67/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/d5d3/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/e0a2/hdl" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/571c/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../dma_sys.srcs/sources_1/bd/dma_sys/ipshared/19b5/hdl/verilog" "+incdir+C:/Xilinx/Vivado/2017.3/data/xilinx_vip/include" \
"../../../../dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_auto_pc_0/sim/dma_sys_auto_pc_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

