# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Developer/dma_sys/dma_sys.cache/wt [current_project]
set_property parent.project_path D:/Developer/dma_sys/dma_sys.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths d:/Developer/dmaSystem/ip_repo [current_project]
set_property ip_output_repo d:/Developer/dma_sys/dma_sys.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/hdl/dma_sys_wrapper.v
add_files D:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/dma_sys.bd
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_processing_system7_0_0/dma_sys_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_dma_0_0/dma_sys_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_rst_ps7_0_50M_0/dma_sys_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_rst_ps7_0_50M_0/dma_sys_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_rst_ps7_0_50M_0/dma_sys_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_10/bd_954e_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_16/bd_954e_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_20/bd_954e_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_21/bd_954e_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_22/bd_954e_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_23/bd_954e_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_24/bd_954e_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_25/bd_954e_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_17/bd_954e_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_18/bd_954e_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_19/bd_954e_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_11/bd_954e_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_12/bd_954e_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_2/bd_954e_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_3/bd_954e_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_4/bd_954e_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_5/bd_954e_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_6/bd_954e_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_1/bd_954e_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_1/bd_954e_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/ip/ip_0/bd_e02d_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/bd_0/bd_e02d_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_system_ila_0_0/dma_sys_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_auto_pc_0/dma_sys_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/dma_sys_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top dma_sys_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dma_sys_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dma_sys_wrapper_utilization_synth.rpt -pb dma_sys_wrapper_utilization_synth.pb"
