# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/dma_sys_axi_smc_1.xci
# IP: The module: 'dma_sys_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/bd_954e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_10/bd_954e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_16/bd_954e_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_20/bd_954e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_26/bd_954e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_21/bd_954e_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_22/bd_954e_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_23/bd_954e_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_24/bd_954e_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_25/bd_954e_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_17/bd_954e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_18/bd_954e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_19/bd_954e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_13/bd_954e_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_14/bd_954e_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_15/bd_954e_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_11/bd_954e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_12/bd_954e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_7/bd_954e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_8/bd_954e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_9/bd_954e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_2/bd_954e_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_3/bd_954e_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_4/bd_954e_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_5/bd_954e_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_6/bd_954e_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_0/bd_954e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_1/bd_954e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_10/bd_954e_s00a2s_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_16/bd_954e_s01a2s_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_20/bd_954e_m00s2a_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_21/bd_954e_m00arn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_22/bd_954e_m00rn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_23/bd_954e_m00awn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_24/bd_954e_m00wn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_25/bd_954e_m00bn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_17/bd_954e_sawn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_18/bd_954e_swn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_19/bd_954e_sbn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_11/bd_954e_sarn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_12/bd_954e_srn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_2/bd_954e_arsw_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_3/bd_954e_rsw_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_4/bd_954e_awsw_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_5/bd_954e_wsw_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_6/bd_954e_bsw_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_1/bd_954e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_1/bd_954e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/dma_sys_axi_smc_1.xci
# IP: The module: 'dma_sys_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/bd_954e.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_10/bd_954e_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_16/bd_954e_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_20/bd_954e_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_26/bd_954e_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_21/bd_954e_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_22/bd_954e_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_23/bd_954e_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_24/bd_954e_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_25/bd_954e_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_17/bd_954e_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_18/bd_954e_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_19/bd_954e_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_13/bd_954e_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_14/bd_954e_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_15/bd_954e_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_11/bd_954e_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_12/bd_954e_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_7/bd_954e_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_8/bd_954e_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_9/bd_954e_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_2/bd_954e_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_3/bd_954e_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_4/bd_954e_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_5/bd_954e_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_6/bd_954e_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_0/bd_954e_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_1/bd_954e_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_10/bd_954e_s00a2s_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_16/bd_954e_s01a2s_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_20/bd_954e_m00s2a_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_21/bd_954e_m00arn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_22/bd_954e_m00rn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_23/bd_954e_m00awn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_24/bd_954e_m00wn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_25/bd_954e_m00bn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_17/bd_954e_sawn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_18/bd_954e_swn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_19/bd_954e_sbn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_11/bd_954e_sarn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_12/bd_954e_srn_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_2/bd_954e_arsw_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_3/bd_954e_rsw_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_4/bd_954e_awsw_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_5/bd_954e_wsw_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_6/bd_954e_bsw_0_ooc.xdc

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_1/bd_954e_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/bd_0/ip/ip_1/bd_954e_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/Developer/dma_sys/dma_sys.srcs/sources_1/bd/dma_sys/ip/dma_sys_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_sys_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
